# Generated by Django 4.1 on 2022-09-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Livros',
        ),
    ]
