# Generated by Django 4.1 on 2022-09-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_rename_contato_livros'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
