# Generated by Django 4.1 on 2022-09-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_alter_livros_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='resenha',
            field=models.TextField(),
        ),
    ]
