# Generated by Django 4.1 on 2022-09-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0007_alter_livros_resenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
