# Generated by Django 4.1 on 2022-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0008_alter_livros_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
