# Generated by Django 4.1 on 2022-09-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0011_coolmodelbro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoolModelBro',
        ),
    ]
