# Generated by Django 4.1 on 2022-10-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0012_delete_coolmodelbro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='avaliacao',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
