# Generated by Django 4.1 on 2022-10-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0013_alter_livros_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='avaliacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
