# Generated by Django 4.1 on 2022-10-03 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0015_alter_livros_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='avaliacao',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
